FROM archlinux:latest

RUN yes | pacman -Sy reflector rsync
RUN reflector --latest 20 --protocol http --protocol https --sort rate --save /etc/pacman.d/mirrorlist --verbose


RUN yes | pacman -S --needed tmux neovim nodejs ripgrep python zsh curl git

ENTRYPOINT ["tail"]
CMD ["-f","/dev/null"]
