FROM  fedora:latest

RUN dnf install -y 'dnf-command(config-manager)'
RUN dnf config-manager --setopt=deltarpm=True --save
RUN dnf config-manager --setopt=fastestmirror=True --save
RUN dnf makecache --refresh

RUN dnf install -y tmux neovim nodejs ripgrep python zsh curl git

ENTRYPOINT ["tail"]
CMD ["-f","/dev/null"]
