FROM archlinux:latest

RUN yes | pacman -Sy reflector rsync
RUN reflector -c BR --sort rate -a 6 --save /etc/pacman.d/mirrorlist --verbose

RUN yes | pacman -S --needed tmux neovim nodejs ripgrep python zsh curl git mono mono-msbuild dotnet-runtime dotnet-sdk

ENTRYPOINT ["tail"]
CMD ["-f","/dev/null"]
