FROM archlinux:latest

RUN yes | pacman -Sy reflector rsync
RUN reflector --latest 20 --protocol http --protocol https --sort rate --save /etc/pacman.d/mirrorlist --verbose

RUN yes | pacman -S --needed tmux neovim nodejs ripgrep python tree zsh curl git \
  #dotnet-sdk \ # for c charp development 

RUN git clone --depth 1 https://github.com/marcosfnsc/setups.git

ENTRYPOINT ["tail"]
CMD ["-f","/dev/null"]
