FROM archlinux:latest

RUN yes | pacman -Sy reflector rsync
RUN reflector -c BR --sort rate -a 6 --save /etc/pacman.d/mirrorlist --verbose

RUN yes | pacman -S --needed tmux neovim nodejs ripgrep python zsh curl git

RUN git clone --depth 1 https://github.com/marcosfnsc/setups.git
RUN cd setups/docker_dev_setup && ./setup_dev_environ.sh

ENTRYPOINT ["tail"]
CMD ["-f","/dev/null"]
